---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: install Apache httpd
      yum:
        name: httpd
        state: present        
    - name: Start & Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes        
    - name: Deploy web file
      copy:
         src: index.html
         dest: /var/www/html/index.html
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
#  vars:
#    dbname: groups
#    dbuser: devops
#    dbpass: admin123
  tasks:
    - debug:
         var: dbname
    - debug:
          msg: "The value of your username is {{dbname}}"
    - name: Install Mariadb
      yum:
          name: mariadb-server
          state: present
    - name: Install Python MYSQL
      yum: 
        name: MySQL-python
        state: present
    - name: Start MySQL
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
           name: "{{dbname}}"
           state: present

    - name: Create a user with name 'admin'
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
