apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-main
  labels: 
    app: {{ .Release.Name }}-{{ .Chart.Name }}-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-main
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-main
        image: {{ .Values.image.main.repository }}:{{ .Values.image.main.tag }}
        imagePullPolicy: Always
        ports:
        - name: enodeapi-port
          containerPort: 5000
      imagePullSecrets:
      - name: regcred 
     
