apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-backend
spec:
  ingressClassName: nginx
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path.main }}
        pathType: Prefix
        backend:
          service:
           name: {{ .Release.Name }}-{{ .Chart.Name }}-main
           port: 
             number: 5000
      - path: {{ .Values.ingress.path.books }}
        pathType: Prefix
        backend:
          service:
           name: {{ .Release.Name }}-{{ .Chart.Name }}-books
           port: 
             number: 9000
