apiVersion: v1
kind: Service
metadata:
  name: emongo
spec:
  ports:
  - port: {{ .Values.service.mongo.port }}
    targetPort: 27017
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-mongo
  type: {{ .Values.service.mongo.type }}
