apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-client
  labels: 
    app: {{ .Release.Name }}-{{ .Chart.Name }}-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-client
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-client
        image: {{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}
        imagePullPolicy: Always
        ports:
        - name: eclient-port
          containerPort: 4200
      imagePullSecrets:
      - name: regcred 
     
