---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: install Apache httpd
      yum:
        name: httpd
        state: present        
    - name: Start & Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes        
    - name: Deploy web file
      copy:
         src: index.html
         dest: /var/www/html/index.html
- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: install Apache httpd
      yum:
        name: mariadb-server
        state: present

